/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetres;

import Classes.Bateau;
import Classes.BateauAmarre;
import Classes.Equipage;
import Classes.FichierLog;
import Classes.Marin;
import Classes.Ponton;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Vector;

/**
 *
 * @author ASUS7
 */
public class RechercheMarin extends javax.swing.JDialog {
    Vector<Ponton> listesP;

    /**
     * Creates new form RechercheMarin
     */
    public RechercheMarin(java.awt.Frame parent, boolean modal, Vector<Ponton> listePontons) {
        super(parent, modal);
        initComponents();
        
        if (listePontons != null)
            listesP = listePontons;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTfNomMarin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTfPrenom = new javax.swing.JTextField();
        jBtnChercher = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLblFonction = new javax.swing.JLabel();
        jLblDate = new javax.swing.JLabel();
        jBtnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Encodez le nom du marin");

        jLabel2.setText("Encodez le prenom du marin");

        jBtnChercher.setText("Chercher");
        jBtnChercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChercherActionPerformed(evt);
            }
        });

        jLabel3.setText("Fonction : ");

        jLabel4.setText("Date de naissance : ");

        jBtnOk.setText("Ok");
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTfNomMarin)
                    .addComponent(jTfPrenom)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnChercher))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblFonction))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblDate)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jBtnOk)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTfNomMarin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTfPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnChercher)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLblFonction))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jBtnOk)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnChercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnChercherActionPerformed
        String nom = jTfNomMarin.getText();
        String prenom = jTfPrenom.getText();
        
        if (!"".equals(nom) && !"".equals(prenom)) {
            Marin marin = searchMarinBat(listesP, nom, prenom);
            
            if (marin != null) {
                jLblFonction.setText(marin.getFonction());
                
                String pattern = "MM/dd/yyyy";
                DateFormat df = new SimpleDateFormat(pattern);
                String dateAsString = df.format(marin.getDateNaissance());
                jLblDate.setText(dateAsString);
                
                FichierLog.Writer("RechercheBateau", "Affichage d'un marin");
            }
        }
    }//GEN-LAST:event_jBtnChercherActionPerformed

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnOkActionPerformed

    private Marin searchMarinBat(Vector<Ponton> list, String nomMarin, String prenomMarin) {
        Enumeration enm = list.elements();
        Bateau bat;
        ArrayList<BateauAmarre> listBateaux = new ArrayList<BateauAmarre>();
        
        int a = 0;
        for (int i = 0; enm.hasMoreElements(); i++) {
            Ponton unPonton = (Ponton) enm.nextElement();
            for (int j = 0; i < 2; j++) {
                for (int k = 0; k < unPonton.getNombreEmplacements(); k++) {
                    bat = (Bateau) unPonton.getListe(i + 1)[k];
                    
                    if (bat.getEquipage().getCapitaine().getNom().equals(nomMarin) && bat.getEquipage().getCapitaine().getPrenom().equals(prenomMarin))
                        return bat.getEquipage().getCapitaine();
                    
                    else if (bat.getEquipage().getSecond().getNom().equals(nomMarin) && bat.getEquipage().getSecond().getPrenom().equals(prenomMarin))
                        return bat.getEquipage().getSecond();
                    
                    else {
                        for (Marin m : bat.getEquipage().getLiMarins()) {
                            if (m.getNom().equals(nomMarin) && m.getPrenom().equals(prenomMarin))
                                return m;
                        }
                    }
                    
                    
                }
            }
        }
        
        FichierLog.Writer("RechercheMarin", "Recherche d'un marin");
        return null;
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RechercheMarin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RechercheMarin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RechercheMarin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RechercheMarin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RechercheMarin dialog = new RechercheMarin(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnChercher;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblDate;
    private javax.swing.JLabel jLblFonction;
    private javax.swing.JTextField jTfNomMarin;
    private javax.swing.JTextField jTfPrenom;
    // End of variables declaration//GEN-END:variables
}
