/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetres;

import Classes.Bateau;
import Classes.BateauAmarre;
import Classes.Equipage;
import Classes.FichierLog;
import Classes.Marin;
import Classes.Ponton;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Enumeration;
import java.util.Vector;
import javax.swing.DefaultListModel;

/**
 *
 * @author ASUS7
 */
public class RechercheBateau extends javax.swing.JDialog {
    
    Vector<Ponton> listesP;
    /**
     * Creates new form RechercheBateau
     */
    public RechercheBateau(java.awt.Frame parent, boolean modal, Vector<Ponton> listePontons) {
        super(parent, modal);
        initComponents();
        
        if (listePontons != null)
            listesP = listePontons;
            
    }
    
    
    private Bateau searchBatAmarre(Vector<Ponton> list, String nomBat) {
        Enumeration enm = list.elements();
        Bateau bat;
        ArrayList<BateauAmarre> listBateaux = new ArrayList<BateauAmarre>();
        
        int a = 0;
        for (int i = 0; enm.hasMoreElements(); i++) {
            Ponton unPonton = (Ponton) enm.nextElement();
            for (int j = 0; j < 2; j++) {
                for (int k = 0; k < unPonton.getNombreEmplacements(); k++) {
                    bat = (Bateau) unPonton.getListe(j + 1)[k];
                    
                    System.out.println("bat = " + bat + "    nomBat = " + nomBat);
                    
                    if (bat != null)
                        if (bat.getNom().equals(nomBat))
                            return bat;
                }
            }
        }
        return null;
    }
    
    private void AfficheBateau(Bateau bat) {
        jLblLongueur.setText(String.valueOf(bat.getLongueur()) );
        jLblPavillon.setText(bat.getPavillon());
        
        
        String pattern = "MM/dd/yyyy HH:mm:ss";
        DateFormat df = new SimpleDateFormat(pattern);
        String dateAsString = df.format(bat.getDateArriver());
        
        
        jLblDate.setText(dateAsString);
        
        AfficheEquip(bat.getEquipage());
        
        FichierLog.Writer("RechercheBateau", "Affichage de bateau");
    }
    
    private void AfficheEquip (Equipage equip) {
        DefaultListModel dlm = new DefaultListModel<>();
        
        if (equip.getCapitaine().getNom() != "inconnu") 
            dlm.addElement(equip.getCapitaine());
        
        if (equip.getSecond().getNom() != "inconnu") 
            dlm.addElement(equip.getSecond());
        
        for (Marin m : equip.getLiMarins()) {
            dlm.addElement(m);
        }
        
        jListEquipage.setModel(dlm);
        
        FichierLog.Writer("RechercheBateau", "Affichage d'equipe");
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextNomBat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLblddLongueur = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEquipage = new javax.swing.JList();
        jLblLongueur = new javax.swing.JLabel();
        jLblPavillon = new javax.swing.JLabel();
        jLblDate = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jBtnChercher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Encodez le nom du bateau");

        jLblddLongueur.setText("Longueur : ");

        jLabel3.setText("Pavillon : ");

        jLabel4.setText("Date d'arrivée : ");

        jLabel5.setText("Equipage : ");

        jScrollPane1.setViewportView(jListEquipage);

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jBtnChercher.setText("Chercher");
        jBtnChercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChercherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jButtonOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextNomBat)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblddLongueur)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblLongueur))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblPavillon))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblDate)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnChercher)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNomBat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnChercher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblddLongueur)
                    .addComponent(jLblLongueur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLblPavillon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jBtnChercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnChercherActionPerformed
        String nomBat = jTextNomBat.getText();
        Bateau bat = searchBatAmarre(listesP, nomBat);
        if (bat != null)
            AfficheBateau(bat);
        
        FichierLog.Writer("RechercheBateau", "Recherche de bateau");
    }//GEN-LAST:event_jBtnChercherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RechercheBateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RechercheBateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RechercheBateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RechercheBateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RechercheBateau dialog = new RechercheBateau(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnChercher;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblDate;
    private javax.swing.JLabel jLblLongueur;
    private javax.swing.JLabel jLblPavillon;
    private javax.swing.JLabel jLblddLongueur;
    private javax.swing.JList jListEquipage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextNomBat;
    // End of variables declaration//GEN-END:variables
}
