/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetres;

import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.RootPaneContainer;

import Classes.Bateau;
import Classes.Equipage;
import Classes.Marin;
import javax.swing.ImageIcon;

/**
 *
 * @author ASUS7
 */
public class WinBateauAmarre extends javax.swing.JDialog {


    java.awt.Frame parentWindow;

    Marin p1 = new Marin("Turner", "Will", "", "Passager");
    Marin p2 = new Marin("Swan", "Elizabeth", "", "Passager");
    List<Marin> psg = new ArrayList<Marin>();
    
    Bateau bateau;
    Equipage eqip = new Equipage();

    public WinBateauAmarre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        parentWindow = parent;
        initComponents();
        setLocation(parent);


        
        initValues();
    }

    public WinBateauAmarre(java.awt.Frame parent, boolean modal, Bateau bat) {
        super(parent, modal);

        parentWindow = parent;
        initComponents();
        setLocation(parent);

        bateau = bat;

        jLabelNomBat.setText(bateau.getNom());
        setIcon();
    }
    
    public final void setIcon()
    {
        String str = System.getProperty("user.dir") + System.getProperty("file.separator") + "images" + System.getProperty("file.separator") + "Eng_flag.jpg";
        ImageIcon image = new ImageIcon(str);
        jLabelFlag.setText(null);
        jLabelFlag.setIcon(image);
    }



    private void initValues() {
        psg.add(p1);
        psg.add(p2);

        Marin cap = new Marin("Saprrow", "Jack", "", "Capitaine");
        Marin sec = new Marin("Barbossa", "Hector", "", "Second");

        eqip = new Equipage(psg, cap, sec);

        bateau = new Bateau("Black Pearl", "Caraibes", 30, 50, "Tortuga", eqip);

        jLabelNomBat.setText(bateau.getNom());
        jTxtf_PortAtache.setText(bateau.getPortAttache());
        jTxtfTonnage.setText(String.valueOf(bateau.getTonnage()));

        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) this.jComboBoxEquip.getModel();
        comboModel.removeAllElements();

        comboModel.addElement(bateau.getEquipage().getCapitaine());
        // Marin secc = bateau.getEquipage().getSecond();
        if (sec != null)
            comboModel.addElement(bateau.getEquipage().getSecond());
        for (Marin m : bateau.getEquipage().getLiMarins()) {
            comboModel.addElement(m);
        }
    }

    private void setLocation(java.awt.Frame parent) {
        int posX = parent.getLocation().x + ((RootPaneContainer) parent).getContentPane().getSize().height / 2;
        this.setLocation(posX,  parent.getLocation().y + 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelNomBat = new javax.swing.JLabel();
        jLabelFlag = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtf_PortAtache = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtfTonnage = new javax.swing.JTextField();
        btnEquipage = new javax.swing.JButton();
        jComboBoxEquip = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        btnOk = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Emplacement : ");

        jLabel2.setText("Bateau : ");

        jLabel3.setText("Pavillon : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Q2*4");

        jLabelNomBat.setText("Marie Hurlante");

        jLabelFlag.setText("Image");

        jLabel7.setText("Port d'atache : ");

        jLabel8.setText("Tonnage : ");

        btnEquipage.setText("Equipage");
        btnEquipage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipageActionPerformed(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEquipage)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtf_PortAtache))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabelNomBat)
                            .addComponent(jLabelFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxEquip, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtfTonnage)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jSeparator1)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnAnnuler)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelNomBat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtf_PortAtache, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtfTonnage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEquipage)
                    .addComponent(jComboBoxEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnAnnuler))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnEquipageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipageActionPerformed
        WinEquipage win = new WinEquipage(parentWindow, true, bateau.getEquipage());
        win.setVisible(true);

        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) this.jComboBoxEquip.getModel();
        comboModel.removeAllElements();

        if (bateau.getEquipage().getCapitaine().getNom() != "inconnu")
            comboModel.addElement(bateau.getEquipage().getCapitaine());
        if (bateau.getEquipage().getSecond().getNom() != "inconnu")
            comboModel.addElement(bateau.getEquipage().getSecond());
        for (Marin m : bateau.getEquipage().getLiMarins()) {
            comboModel.addElement(m);
        }
    }//GEN-LAST:event_btnEquipageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinBateauAmarre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinBateauAmarre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinBateauAmarre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinBateauAmarre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WinBateauAmarre dialog = new WinBateauAmarre(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnEquipage;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox jComboBoxEquip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelFlag;
    private javax.swing.JLabel jLabelNomBat;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxtfTonnage;
    private javax.swing.JTextField jTxtf_PortAtache;
    // End of variables declaration//GEN-END:variables
}
