/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetres;

import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

import javax.swing.RootPaneContainer;

import Classes.Equipage;
import Classes.FichierLog;
// import Classes.Marin;
import Classes.Marin;

/**
 *
 * @author ASUS7
 */
public class WinEquipage extends javax.swing.JDialog {

    /**
     * Creates new form WinEquipage
     */
    Equipage equip;
    List<Marin> listMarin = new ArrayList<>();


    public WinEquipage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public WinEquipage(java.awt.Frame parent, boolean modal, Equipage equipage) {
        super(parent, modal);
        initComponents();
        setLocation(parent);

        equip = equipage;
        initList();
    }

    private void setLocation(java.awt.Frame parent) {
        int posX = parent.getLocation().x + ((RootPaneContainer) parent).getContentPane().getSize().height / 2;
        this.setLocation(posX,  parent.getLocation().y + 100);
    }

    private void initList() {
        DefaultListModel dlm = new DefaultListModel<>();
        if (equip.getCapitaine().getNom() != "inconnu") {
            dlm.addElement(equip.getCapitaine());
            jRadioBtnCapitaine.setEnabled(false);
        }
            
        if (equip.getSecond().getNom() != "inconnu") {
            dlm.addElement(equip.getSecond());
            jRadioBtnSecond.setEnabled(false);
        }
            
        
        // System.out.println(equip.getLiMarins());
        for (Marin m : equip.getLiMarins()) {
            dlm.addElement(m);
        }

        this.jListEquipage.setModel(dlm);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPrenom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDateNaissance = new javax.swing.JTextField();
        jRadioBtnCapitaine = new javax.swing.JRadioButton();
        jRadioBtnSecond = new javax.swing.JRadioButton();
        jRadioBtnBosco = new javax.swing.JRadioButton();
        jRadioBtnMatelot = new javax.swing.JRadioButton();
        jRadioBtnPassager = new javax.swing.JRadioButton();
        btnOk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEquipage = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        btnValider = new javax.swing.JButton();
        btnAbondonner = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Bateau : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Marie Hurlante(Norwich)");

        jLabel3.setText("Nom : ");

        jLabel4.setText("Prénom : ");

        jLabel5.setText("Date de naissance : ");

        buttonGroup1.add(jRadioBtnCapitaine);
        jRadioBtnCapitaine.setText("Capitaine");

        buttonGroup1.add(jRadioBtnSecond);
        jRadioBtnSecond.setText("Second");

        buttonGroup1.add(jRadioBtnBosco);
        jRadioBtnBosco.setText("Bosco");

        buttonGroup1.add(jRadioBtnMatelot);
        jRadioBtnMatelot.setText("Matelot");

        buttonGroup1.add(jRadioBtnPassager);
        jRadioBtnPassager.setText("Passager");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jListEquipage.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListEquipage.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListEquipageValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListEquipage);

        btnValider.setText("Valider équipage");
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });

        btnAbondonner.setText("Abondonner");
        btnAbondonner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbondonnerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(68, 68, 68)
                                                .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jTextFieldDateNaissance, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(12, 12, 12))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioBtnMatelot)
                                    .addComponent(jRadioBtnCapitaine))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioBtnPassager)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioBtnSecond)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioBtnBosco)))))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnValider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAbondonner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioBtnCapitaine)
                            .addComponent(jRadioBtnSecond)
                            .addComponent(jRadioBtnBosco)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioBtnMatelot)
                    .addComponent(jRadioBtnPassager))
                .addGap(18, 18, 18)
                .addComponent(btnOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValider)
                    .addComponent(btnAbondonner))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListEquipageValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListEquipageValueChanged
        System.out.print("value changed");
    }//GEN-LAST:event_jListEquipageValueChanged



    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        String nom = jTextFieldNom.getText();
        String prenom = jTextFieldPrenom.getText();
        String dateDeNaiss = jTextFieldDateNaissance.getText();
        String fonction = getSelectedRadioBtn();
        clearTextBox();

        Marin m = new Marin(nom, prenom, dateDeNaiss, fonction);

        listMarin.add(m);

        DefaultListModel comboModel = (DefaultListModel) this.jListEquipage.getModel();
        
        comboModel.addElement(m);
    }//GEN-LAST:event_btnOkActionPerformed

    private void clearTextBox() {
        jTextFieldNom.setText("");
        jTextFieldPrenom.setText("");
        jTextFieldDateNaissance.setText("");
    }



    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        for (Marin m : listMarin) {
            if (m.getFonction() == "Second") {
                equip.setSecond(m);
            }
            else if (m.getFonction() == "Capitaine"){
                equip.setCapitaine(m);
            }
            else {
                equip.getLiMarins().add(m);
            }
        }
        
        FichierLog.Writer("WinEquipage", "Ajout d'equipage dans bateau");
        this.dispose();
    }//GEN-LAST:event_btnValiderActionPerformed

    private void btnAbondonnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbondonnerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAbondonnerActionPerformed

    private String getSelectedRadioBtn() {
        if (jRadioBtnCapitaine.isSelected()) {
            jRadioBtnCapitaine.setEnabled(false);
            return "Capitaine";
        }
        if (jRadioBtnSecond.isSelected()) {
            jRadioBtnSecond.setEnabled(false);
            return "Second";
        }
        if (jRadioBtnBosco.isSelected())
            return "Bosco";
        if (jRadioBtnMatelot.isSelected())
            return "Matelot";
        if (jRadioBtnPassager.isSelected())
            return "Passager";

        return null;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinEquipage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinEquipage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinEquipage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinEquipage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WinEquipage dialog = new WinEquipage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbondonner;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnValider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jListEquipage;
    private javax.swing.JRadioButton jRadioBtnBosco;
    private javax.swing.JRadioButton jRadioBtnCapitaine;
    private javax.swing.JRadioButton jRadioBtnMatelot;
    private javax.swing.JRadioButton jRadioBtnPassager;
    private javax.swing.JRadioButton jRadioBtnSecond;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldDateNaissance;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    // End of variables declaration//GEN-END:variables
}
